error-reporting-email: {{email}}
background-indexing-enabled: true
background-linking-indexing-enabled: false
background-deletion-enabled: true
background-expired-data-deletion-enabled: true
background-external-database-syncing-enabled: true
search:
  elasticsearchUrl: {{elasticsearch-host}}
  elasticsearchCluster: {{cluster-name}}
  elasticsearchPort: 9300
  elasticsearchRestPort: 9200