entity-type: "ol.audit"
edge-entity-type: "ol.audited"
fqns:
  ACL_KEY: "ol.key"
  DATA: "ol.details"
  DESCRIPTION: "ol.description"
  ENTITY_SETS: "ol.target"
  ENTITIES: "ol.objectid"
  EVENT_TYPE: "ol.type"
  ID: "ol.id"
  PRINCIPAL: "ol.userid"
  TIMESTAMP: "general.datetime"
  OPERATION_ID: "ol.id"
aws:
  bucket: "{{audit-storage-bucket}}"
  regionName: "{{region}}"
  accessKeyId: "{{audit-user-access-key-id}}"
  secretAccessKey: "{{audit-user-secret-access-key}}"
